1515529589.53
09-Jan-2018 20:26:29 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:26:29 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:26:29 (+0000) INFO: args: ()
09-Jan-2018 20:26:29 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:26:29 (+0000) INFO: board ID (random): 241
09-Jan-2018 20:26:29 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:26:30 (+0000) INFO: board ID (random): 123
09-Jan-2018 20:26:30 (+0000) INFO: starting scan
09-Jan-2018 20:26:30 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:26:30 (+0000) INFO: gap in packets, between 60064 and 60110 packet before: [6, 2, 1, 160, 234, 14, 12, 0] packet after: [6, 36, 1, 206, 234, 6, 10, 1, 37, 70, 0, 0, 202, 76, 0, 0, 214, 190, 137, 142, 64, 17, 110, 31, 48, 43, 130, 108, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 185, 205, 125]
09-Jan-2018 20:26:31 (+0000) INFO: gap in packets, between 60197 and 60199 packet before: [6, 48, 1, 37, 235, 6, 10, 1, 38, 68, 0, 0, 100, 1, 0, 0, 214, 190, 137, 142, 64, 29, 90, 8, 226, 241, 26, 105, 2, 1, 6, 19, 255, 76, 0, 12, 14, 0, 49, 194, 142, 21, 243, 200, 9, 235, 2, 171, 237, 24, 248, 52, 57, 109] packet after: [6, 36, 1, 39, 235, 6, 10, 1, 37, 72, 0, 0, 53, 112, 0, 0, 214, 190, 137, 142, 64, 17, 110, 31, 48, 43, 130, 108, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 185, 205, 125]
09-Jan-2018 20:26:31 (+0000) INFO: gap in packets, between 60199 and 14040 packet before: [6, 36, 1, 39, 235, 6, 10, 1, 37, 72, 0, 0, 53, 112, 0, 0, 214, 190, 137, 142, 64, 17, 110, 31, 48, 43, 130, 108, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 185, 205, 125] packet after: [6, 39, 1, 216, 54, 6, 10, 1, 37, 72, 0, 0, 164, 128, 0, 0, 214, 190, 137, 142, 64, 20, 40, 183, 198, 145, 38, 75, 2, 1, 26, 10, 255, 76, 0, 16, 5, 1, 144, 211, 1, 34, 30, 173, 153]
09-Jan-2018 20:26:31 (+0000) INFO: gap in packets, between 14062 and 14080 packet before: [6, 36, 1, 238, 54, 6, 10, 1, 38, 81, 0, 0, 94, 1, 0, 0, 214, 190, 137, 142, 0, 17, 122, 130, 150, 50, 188, 172, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 239, 53, 104] packet after: [6, 2, 1, 0, 55, 14, 12, 0]
09-Jan-2018 20:26:35 (+0000) INFO: starting scan
09-Jan-2018 20:26:35 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:26:59 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:26:59 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:26:59 (+0000) INFO: args: ()
09-Jan-2018 20:26:59 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:26:59 (+0000) INFO: board ID (random): 89
09-Jan-2018 20:26:59 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:27:00 (+0000) INFO: board ID (random): 155
09-Jan-2018 20:27:00 (+0000) INFO: starting scan
09-Jan-2018 20:27:00 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:00 (+0000) INFO: gap in packets, between 15128 and 15165 packet before: [6, 2, 1, 24, 59, 14, 12, 0] packet after: [6, 2, 1, 61, 59, 14, 12, 0]
09-Jan-2018 20:27:01 (+0000) INFO: gap in packets, between 15325 and 15333 packet before: [6, 39, 1, 221, 59, 6, 10, 1, 37, 71, 0, 0, 227, 143, 2, 0, 214, 190, 137, 142, 64, 20, 226, 164, 6, 18, 67, 105, 2, 1, 26, 10, 255, 76, 0, 16, 5, 10, 16, 5, 208, 87, 54, 251, 195] packet after: [6, 2, 1, 229, 59, 14, 12, 0]
09-Jan-2018 20:27:01 (+0000) INFO: gap in packets, between 15333 and 15726 packet before: [6, 2, 1, 229, 59, 14, 12, 0] packet after: [6, 39, 1, 110, 61, 6, 10, 1, 37, 75, 0, 0, 61, 70, 1, 0, 214, 190, 137, 142, 64, 20, 226, 164, 6, 18, 67, 105, 2, 1, 26, 10, 255, 76, 0, 16, 5, 10, 16, 5, 208, 87, 54, 251, 195]
09-Jan-2018 20:27:01 (+0000) INFO: gap in packets, between 15752 and 15756 packet before: [6, 2, 1, 136, 61, 14, 12, 0] packet after: [6, 2, 1, 140, 61, 14, 12, 0]
09-Jan-2018 20:27:01 (+0000) INFO: gap in packets, between 15756 and 15759 packet before: [6, 2, 1, 140, 61, 14, 12, 0] packet after: [6, 2, 1, 143, 61, 14, 12, 0]
09-Jan-2018 20:27:05 (+0000) INFO: starting scan
09-Jan-2018 20:27:05 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:10 (+0000) ERROR: UART read error
Traceback (most recent call last):
  File "/home/pi/watch/SnifferAPI/SnifferCollector.py", line 152, in _continuouslyPipe
    packet = self._packetReader.getPacket(timeout = 2)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 161, in getPacket
    packetList = self.decodeFromSLIP(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 126, in decodeFromSLIP
    serialByte = self.getSerialByte(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 146, in getSerialByte
    serialByte = self.uart.readByte(timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 58, in readByte
    readString = self.read(1, timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 47, in read
    value = self.ser.read(length)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 515, in read
    raise SerialException('read failed: {}'.format(e))
SerialException: read failed: (9, 'Bad file descriptor')
09-Jan-2018 20:27:17 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:27:17 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:27:17 (+0000) INFO: args: ()
09-Jan-2018 20:27:17 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:27:17 (+0000) INFO: board ID (random): 248
09-Jan-2018 20:27:17 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:27:18 (+0000) INFO: board ID (random): 150
09-Jan-2018 20:27:18 (+0000) INFO: starting scan
09-Jan-2018 20:27:18 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:18 (+0000) INFO: gap in packets, between 16226 and 16278 packet before: [6, 2, 1, 98, 63, 14, 12, 0] packet after: [6, 2, 1, 150, 63, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16416 and 16421 packet before: [6, 36, 1, 32, 64, 6, 10, 1, 37, 73, 0, 0, 40, 168, 1, 0, 214, 190, 137, 142, 64, 17, 196, 6, 244, 216, 7, 74, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 184, 185, 168] packet after: [6, 2, 1, 37, 64, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16422 and 16424 packet before: [6, 2, 1, 38, 64, 14, 12, 0] packet after: [6, 2, 1, 40, 64, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16424 and 16505 packet before: [6, 2, 1, 40, 64, 14, 12, 0] packet after: [6, 38, 1, 121, 64, 6, 10, 0, 37, 98, 0, 0, 235, 183, 0, 0, 214, 190, 137, 142, 192, 19, 85, 245, 200, 154, 185, 94, 2, 1, 26, 137, 238, 68, 0, 13, 4, 132, 118, 52, 231, 105, 228, 199]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16531 and 16533 packet before: [6, 36, 1, 147, 64, 6, 10, 1, 38, 80, 0, 0, 94, 1, 0, 0, 214, 190, 137, 142, 64, 17, 196, 6, 244, 216, 7, 74, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 184, 185, 168] packet after: [6, 2, 1, 149, 64, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16533 and 16537 packet before: [6, 2, 1, 149, 64, 14, 12, 0] packet after: [6, 2, 1, 153, 64, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: gap in packets, between 16538 and 16544 packet before: [6, 2, 1, 154, 64, 14, 12, 0] packet after: [6, 2, 1, 160, 64, 14, 12, 0]
09-Jan-2018 20:27:19 (+0000) INFO: starting scan
09-Jan-2018 20:27:19 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:43 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:27:43 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:27:43 (+0000) INFO: args: ()
09-Jan-2018 20:27:43 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:27:43 (+0000) INFO: board ID (random): 10
09-Jan-2018 20:27:43 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:27:44 (+0000) INFO: board ID (random): 82
09-Jan-2018 20:27:44 (+0000) INFO: starting scan
09-Jan-2018 20:27:44 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:44 (+0000) INFO: gap in packets, between 16834 and 16873 packet before: [6, 2, 1, 194, 65, 14, 12, 0] packet after: [6, 36, 1, 233, 65, 6, 10, 1, 39, 71, 0, 0, 94, 1, 0, 0, 214, 190, 137, 142, 64, 17, 196, 6, 244, 216, 7, 74, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 184, 185, 168]
09-Jan-2018 20:27:44 (+0000) INFO: gap in packets, between 17029 and 17036 packet before: [6, 36, 1, 133, 66, 6, 10, 1, 38, 82, 0, 0, 94, 1, 0, 0, 214, 190, 137, 142, 64, 17, 196, 6, 244, 216, 7, 74, 2, 1, 6, 7, 255, 76, 0, 16, 2, 11, 0, 184, 185, 168] packet after: [6, 2, 1, 140, 66, 14, 12, 0]
09-Jan-2018 20:27:44 (+0000) INFO: gap in packets, between 17037 and 17567 packet before: [6, 2, 1, 141, 66, 14, 12, 0] packet after: [6, 39, 1, 159, 68, 6, 10, 1, 39, 72, 0, 0, 202, 232, 0, 0, 214, 190, 137, 142, 64, 20, 226, 164, 6, 18, 67, 105, 2, 1, 26, 10, 255, 76, 0, 16, 5, 10, 16, 5, 208, 87, 54, 251, 195]
09-Jan-2018 20:27:46 (+0000) INFO: starting scan
09-Jan-2018 20:27:46 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:27:59 (+0000) INFO: starting scan
09-Jan-2018 20:27:59 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:03 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:28:03 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:28:03 (+0000) INFO: args: ()
09-Jan-2018 20:28:03 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:28:03 (+0000) INFO: board ID (random): 154
09-Jan-2018 20:28:03 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:28:04 (+0000) INFO: board ID (random): 124
09-Jan-2018 20:28:04 (+0000) INFO: starting scan
09-Jan-2018 20:28:04 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:04 (+0000) INFO: gap in packets, between 19332 and 19348 packet before: [6, 2, 1, 132, 75, 14, 12, 0] packet after: [6, 48, 1, 148, 75, 6, 10, 1, 37, 72, 0, 0, 132, 4, 0, 0, 214, 190, 137, 142, 64, 29, 196, 6, 244, 216, 7, 74, 2, 1, 6, 19, 255, 76, 0, 12, 14, 0, 105, 102, 31, 120, 170, 121, 216, 234, 235, 198, 154, 34, 103, 208, 113, 61]
09-Jan-2018 20:28:06 (+0000) INFO: starting scan
09-Jan-2018 20:28:06 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:12 (+0000) ERROR: UART read error
Traceback (most recent call last):
  File "/home/pi/watch/SnifferAPI/SnifferCollector.py", line 152, in _continuouslyPipe
    packet = self._packetReader.getPacket(timeout = 2)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 161, in getPacket
    packetList = self.decodeFromSLIP(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 126, in decodeFromSLIP
    serialByte = self.getSerialByte(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 146, in getSerialByte
    serialByte = self.uart.readByte(timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 58, in readByte
    readString = self.read(1, timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 47, in read
    value = self.ser.read(length)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 515, in read
    raise SerialException('read failed: {}'.format(e))
SerialException: read failed: (9, 'Bad file descriptor')
09-Jan-2018 20:28:15 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:28:15 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:28:15 (+0000) INFO: args: ()
09-Jan-2018 20:28:15 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:28:15 (+0000) INFO: board ID (random): 80
09-Jan-2018 20:28:15 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
09-Jan-2018 20:28:16 (+0000) INFO: board ID (random): 252
09-Jan-2018 20:28:16 (+0000) INFO: starting scan
09-Jan-2018 20:28:16 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:16 (+0000) INFO: gap in packets, between 19959 and 20012 packet before: [6, 2, 1, 247, 77, 14, 12, 0] packet after: [6, 48, 1, 44, 78, 6, 10, 1, 38, 77, 0, 0, 94, 1, 0, 0, 214, 190, 137, 142, 64, 29, 196, 6, 244, 216, 7, 74, 2, 1, 6, 19, 255, 76, 0, 12, 14, 0, 105, 102, 31, 120, 170, 121, 216, 234, 235, 198, 154, 34, 103, 208, 113, 61]
09-Jan-2018 20:28:18 (+0000) INFO: starting scan
09-Jan-2018 20:28:18 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:23 (+0000) INFO: starting scan
09-Jan-2018 20:28:23 (+0000) INFO: Sent key value to sniffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
09-Jan-2018 20:28:26 (+0000) ERROR: UART read error
Traceback (most recent call last):
  File "/home/pi/watch/SnifferAPI/SnifferCollector.py", line 152, in _continuouslyPipe
    packet = self._packetReader.getPacket(timeout = 2)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 161, in getPacket
    packetList = self.decodeFromSLIP(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 126, in decodeFromSLIP
    serialByte = self.getSerialByte(timeout)
  File "/home/pi/watch/SnifferAPI/Packet.py", line 146, in getSerialByte
    serialByte = self.uart.readByte(timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 58, in readByte
    readString = self.read(1, timeout)
  File "/home/pi/watch/SnifferAPI/UART.py", line 47, in read
    value = self.ser.read(length)
  File "/usr/local/lib/python2.7/dist-packages/serial/serialposix.py", line 515, in read
    raise SerialException('read failed: {}'.format(e))
SerialException: read failed: (9, 'Bad file descriptor')
09-Jan-2018 20:28:30 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:28:30 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:29:59 (+0000) INFO: --------------------------------------------------------
09-Jan-2018 20:29:59 (+0000) INFO: Software version: SVN rev. 1111
09-Jan-2018 20:29:59 (+0000) INFO: args: ()
09-Jan-2018 20:29:59 (+0000) INFO: kwargs: {'callbacks': [('*', <bound method Sniffer.passOnNotification of <Sniffer(Thread-2, initial)>>)]}
09-Jan-2018 20:29:59 (+0000) INFO: board ID (random): 139
09-Jan-2018 20:29:59 (+0000) INFO: Error on port /dev/ttyUSB0. file: Packet.py, line 246: Port is already open.
